version: "3.4"

services:
  db:
    image: postgres:10.6
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend

  backend:
    build:
      context: ./services/backend
      target: backend
    command: ["./scripts/run_local.sh"]
    ports:
      - "5000:5000"
    depends_on:
      - db
      - stripemock
    restart: unless-stopped
    links:
      - db
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-west-1
      - PROJECT_NAME=${PROJECT_NAME}
    stdin_open: true
    tty: true

  workers:
    build:
      context: ./services/workers
    volumes:
      - ./services/webapp/build/email-renderer/:/app/emails/renderer
    depends_on:
      - db
    links:
      - db

  webapp:
    build:
      context: ./services/webapp
    volumes:
      - ./services/webapp/build:/usr/src/app/build/

  e2e:
    build:
      context: ./E2E
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - ENV_STAGE=${ENV_STAGE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - AWS_SESSION_EXPIRATION=${AWS_SESSION_EXPIRATION}
      - CYPRESS_BASIC_AUTH_LOGIN=${CYPRESS_BASIC_AUTH_LOGIN}
      - CYPRESS_BASIC_AUTH_PASSWORD=${CYPRESS_BASIC_AUTH_PASSWORD}
      - CYPRESS_BASIC_AUTH_HEADER=${CYPRESS_BASIC_AUTH_HEADER}

  stripemock:
    image: stripemock/stripe-mock:v0.103.0
    ports:
      - "12111:12111"
      - "12112:12112"
